language: php
php:
- '5.5'
- '5.4'

install:
   - composer install --dev

script:
  - ./vendor/bin/phpcs --standard=PSR2 src/ test/
  - phpunit --bootstrap test/bootstrap.php test/


notifications:
  slack: tatu:ifWJMnOS9BlzH3pxQfJryUUz
